import { z } from 'zod';

export const UserSchema = z.object({
  id: z.string(),
  name: z.string().min(1, { message: "Name is required" }),
  email: z.string().email({ message: "Invalid email address" }),
});

// Schema for registration (without id, as it's generated by the backend, but with password)
export const UserRegistrationSchema = UserSchema.omit({ id: true }).extend({
  password: z.string().min(6, { message: "Password must be at least 6 characters long" })
});
