services:
  db:
    image: postgres:15-alpine
    container_name: taskflow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: taskflow-backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/taskflow
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: 8a4f9b2b9e2c6f3d8a7c1b0e5d4f3b2a9e8c7d6f5a4b3c2d1e0f9b8a7c6d5e4f
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: taskflow-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres-data: