spring:
  application:
    name: taskflow-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true

logging:
  level:
    root: WARN
    #com.lucasdamasceno.taskflow: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
