spring:
  application:
    name: taskflow-backend

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24 hours


  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      root: WARN
        #com.lucasdamasceno.taskflow: DEBUG
